# Generated by Django 5.0.1 on 2024-01-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='zip',
            field=models.CharField(default=20200, max_length=255),
            preserve_default=False,
        ),
    ]
